apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    field.cattle.io/creatorId: user-fvqkl
    field.cattle.io/publicEndpoints: '[{"addresses":["18.206.81.12"],"port":31957,"protocol":"TCP","serviceName":"default:taurus-ldap-nodeport","allNodes":true},{"addresses":["18.206.81.12"],"port":32474,"protocol":"TCP","serviceName":"default:taurus-ldap-nodeport","allNodes":true}]'
  creationTimestamp: "2019-12-17T01:40:54Z"
  generation: 5
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-taurus-ldap
  name: taurus-ldap
  namespace: default
  resourceVersion: "11177"
  selfLink: /apis/apps/v1/namespaces/default/deployments/taurus-ldap
  uid: 444b0f91-fb78-4877-8b53-119b92b9562b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-taurus-ldap
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-12-17T01:48:40Z"
        field.cattle.io/ports: '[[{"containerPort":389,"dnsName":"taurus-ldap-nodeport","kind":"NodePort","name":"389tcp01","protocol":"TCP"},{"containerPort":636,"dnsName":"taurus-ldap-nodeport","kind":"NodePort","name":"636tcp01","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-taurus-ldap
    spec:
      containers:
      - env:
        - name: COMPOSE_HTTP_TIMEOUT
          value: "200"
        - name: LDAP_ADMIN_PASSWORD
          value: admin
        - name: LDAP_BACKEND
          value: hdb
        - name: LDAP_BASE_DN
        - name: LDAP_CONFIG_PASSWORD
          value: config
        - name: LDAP_DOMAIN
          value: taurus.io
        - name: LDAP_LOG_LEVEL
          value: "256"
        - name: LDAP_ORGANISATION
          value: Taurus
        - name: LDAP_READONLY_USER
          value: "false"
        - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
          value: "true"
        - name: LDAP_REPLICATION
          value: "false"
        - name: LDAP_SSL_HELPER_PREFIX
          value: ldap
        - name: LDAP_TLS
          value: "true"
        - name: LDAP_TLS_CA_CRT_FILENAME
          value: ca.crt
        - name: LDAP_TLS_CIPHER_SUITE
          value: SECURE256:-VERS-SSL3.0
        - name: LDAP_TLS_CRT_FILENAME
          value: ldap.crt
        - name: LDAP_TLS_ENFORCE
          value: "false"
        - name: LDAP_TLS_KEY_FILENAME
          value: ldap.key
        - name: LDAP_TLS_PROTOCOL_MIN
          value: "3.1"
        - name: LDAP_TLS_VERIFY_CLIENT
          value: demand
        image: osixia/openldap:1.3.0
        imagePullPolicy: Always
        name: taurus-ldap
        ports:
        - containerPort: 389
          name: 389tcp01
          protocol: TCP
        - containerPort: 636
          name: 636tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-17T01:46:47Z"
    lastUpdateTime: "2019-12-17T01:46:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-17T01:40:54Z"
    lastUpdateTime: "2019-12-17T01:46:47Z"
    message: ReplicaSet "taurus-ldap-7dfd58678f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
