apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    field.cattle.io/creatorId: user-fvqkl
    field.cattle.io/publicEndpoints: '[{"addresses":["18.206.81.12"],"port":30913,"protocol":"TCP","serviceName":"default:taurus-grid-gen-ms-nodeport","allNodes":true}]'
  creationTimestamp: "2019-12-17T00:39:04Z"
  generation: 4
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-taurus-grid-gen-ms
  name: taurus-grid-gen-ms
  namespace: default
  resourceVersion: "679844"
  selfLink: /apis/apps/v1/namespaces/default/deployments/taurus-grid-gen-ms
  uid: dd1c4ddd-66d7-4d93-b271-8b3e3f798f76
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-taurus-grid-gen-ms
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-12-20T00:41:19Z"
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"taurus-grid-gen-ms-nodeport","kind":"NodePort","name":"spring","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-taurus-grid-gen-ms
    spec:
      containers:
      - image: taurusgame/grid-gen-ms
        imagePullPolicy: Always
        name: taurus-grid-gen-ms
        ports:
        - containerPort: 8080
          name: spring
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2019-12-19T21:19:17Z"
    lastUpdateTime: "2019-12-19T21:19:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-17T00:39:04Z"
    lastUpdateTime: "2019-12-20T00:41:28Z"
    message: ReplicaSet "taurus-grid-gen-ms-76d95f789f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
