apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "72"
    field.cattle.io/creatorId: user-fvqkl
    field.cattle.io/publicEndpoints: '[{"addresses":["18.206.81.12"],"port":31016,"protocol":"TCP","serviceName":"default:taurus-game-server-ms-0-nodeport","allNodes":true}]'
  creationTimestamp: "2019-12-17T02:10:30Z"
  generation: 77
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-taurus-game-server-ms-0
  name: taurus-game-server-ms-0
  namespace: default
  resourceVersion: "710224"
  selfLink: /apis/apps/v1/namespaces/default/deployments/taurus-game-server-ms-0
  uid: 1332e73c-dbc3-4b2f-8849-ef158ac2335b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-taurus-game-server-ms-0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-12-20T03:02:23Z"
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"taurus-game-server-ms-0-nodeport","kind":"NodePort","name":"gorilla","protocol":"TCP"}]]'
        workload.cattle.io/state: '{"dGF1cnVzLXJhbmNoZXJhZ2VudC0wLWFsbA==":"c-dpxlj:m-d403bc48cacb"}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-taurus-game-server-ms-0
    spec:
      containers:
      - env:
        - name: API_PREFIX
          value: /gs
        - name: GRAPHQL_URL
          value: http://taurus-gateway:4000/graphql
        - name: MONGO_URL
          value: mongodb://taurus-game-server-db-0:27017,taurus-game-server-db-1:27017,taurus-game-server-db-2:27017,taurus-game-server-db-3:27017/rooms?replicaSet=rs0
        image: taurusgame/game-server-ms
        imagePullPolicy: Always
        name: taurus-game-server-ms-0
        ports:
        - containerPort: 8080
          name: gorilla
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      nodeName: taurus-rancheragent-0-all
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-19T14:43:01Z"
    lastUpdateTime: "2019-12-19T14:43:01Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-17T02:10:30Z"
    lastUpdateTime: "2019-12-20T03:02:26Z"
    message: ReplicaSet "taurus-game-server-ms-0-559d48845b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 77
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
