apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "20"
    field.cattle.io/creatorId: user-fvqkl
    field.cattle.io/publicEndpoints: '[{"addresses":["18.206.81.12"],"port":443,"protocol":"HTTPS","serviceName":"default:taurus-web","ingressName":"default:taurusmaze.co","hostname":"taurusmaze.co","path":"/","allNodes":true}]'
  creationTimestamp: "2019-12-17T01:58:29Z"
  generation: 22
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-taurus-web
  name: taurus-web
  namespace: default
  resourceVersion: "807842"
  selfLink: /apis/apps/v1/namespaces/default/deployments/taurus-web
  uid: daf8170a-c790-40a6-8184-94369b9615ca
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-taurus-web
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-12-20T13:06:58Z"
        field.cattle.io/ports: '[[{"containerPort":5000,"dnsName":"taurus-web","kind":"ClusterIP","name":"react","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-taurus-web
    spec:
      containers:
      - env:
        - name: API_URL
          value: https://taurusmaze.co/graphql
        - name: GAME_WS_URL
          value: https://taurusmaze.co/gs
        - name: REACT_APP_API_URL
          value: https://taurusmaze.co/graphql
        - name: REACT_APP_GAME_API_URL
          value: https://taurusmaze.co/gs
        - name: REACT_APP_GAME_WS_URL
          value: wss://taurusmaze.co/gs
        - name: REACT_APP_SITE_KEY
          value: 6LfkVccUAAAAAFCg3CRQ2kMfEZXDoIqYtXMrQd21
        image: taurusgame/web
        imagePullPolicy: Always
        name: taurus-web
        ports:
        - containerPort: 5000
          name: react
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2019-12-19T21:18:12Z"
    lastUpdateTime: "2019-12-19T21:18:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-17T01:58:29Z"
    lastUpdateTime: "2019-12-20T13:07:07Z"
    message: ReplicaSet "taurus-web-c88f5894b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 22
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
