apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    field.cattle.io/creatorId: user-fvqkl
  creationTimestamp: "2019-12-17T00:47:27Z"
  generation: 6
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-taurus-data-store-db-0
  name: taurus-data-store-db-0
  namespace: default
  resourceVersion: "676126"
  selfLink: /apis/apps/v1/namespaces/default/deployments/taurus-data-store-db-0
  uid: 5620a7b1-afbe-4a99-a7ab-a2941222d6fd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-taurus-data-store-db-0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-12-20T00:22:47Z"
        field.cattle.io/ports: '[[{"containerPort":27017,"dnsName":"taurus-data-store-db-0","kind":"ClusterIP","name":"mongo","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-taurus-data-store-db-0
    spec:
      containers:
      - image: mongo
        imagePullPolicy: Always
        name: taurus-data-store-db-0
        ports:
        - containerPort: 27017
          name: mongo
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-17T00:47:39Z"
    lastUpdateTime: "2019-12-17T00:47:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-17T00:47:27Z"
    lastUpdateTime: "2019-12-20T00:22:49Z"
    message: ReplicaSet "taurus-data-store-db-0-5cd6d85b66" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
