apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    field.cattle.io/creatorId: user-fvqkl
  creationTimestamp: "2019-12-17T02:03:16Z"
  generation: 9
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-taurus-auth-db
  name: taurus-auth-db
  namespace: default
  resourceVersion: "803792"
  selfLink: /apis/apps/v1/namespaces/default/deployments/taurus-auth-db
  uid: b0e294f9-206a-4d55-898c-d7e0e331afaa
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-taurus-auth-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-12-20T12:42:27Z"
        field.cattle.io/ports: '[[{"containerPort":5432,"dnsName":"taurus-auth-db","kind":"ClusterIP","name":"5432tcp02","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-taurus-auth-db
    spec:
      containers:
      - image: postgres
        imagePullPolicy: Always
        name: taurus-auth-db
        ports:
        - containerPort: 5432
          name: 5432tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-17T02:03:26Z"
    lastUpdateTime: "2019-12-17T02:03:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-20T02:49:19Z"
    lastUpdateTime: "2019-12-20T12:42:29Z"
    message: ReplicaSet "taurus-auth-db-ccf8b77db" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
