apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "30"
    field.cattle.io/creatorId: user-fvqkl
    field.cattle.io/publicEndpoints: '[{"addresses":["18.206.81.12"],"port":31574,"protocol":"TCP","serviceName":"default:taurus-stats-ms-nodeport","allNodes":true}]'
  creationTimestamp: "2019-12-17T01:37:47Z"
  generation: 39
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-taurus-stats-ms
  name: taurus-stats-ms
  namespace: default
  resourceVersion: "726540"
  selfLink: /apis/apps/v1/namespaces/default/deployments/taurus-stats-ms
  uid: a517674c-fe7d-480e-a741-63f47c46180b
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-taurus-stats-ms
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-12-20T04:37:00Z"
        field.cattle.io/ports: '[[{"containerPort":5001,"dnsName":"taurus-stats-ms-nodeport","kind":"NodePort","name":"flask","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-taurus-stats-ms
    spec:
      containers:
      - env:
        - name: DB_URL
          value: taurus-stats-db
        - name: MONGO_URL
          value: taurus-stats-mongo-db
        - name: MYSQL_DATABASE
          value: taurus-stats
        - name: MYSQL_PASSWORD
          value: t4urus
        - name: MYSQL_USER
          value: taurus
        image: taurusgame/stats-ms
        imagePullPolicy: Always
        name: taurus-stats-ms
        ports:
        - containerPort: 5001
          name: flask
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2019-12-17T02:20:23Z"
    lastUpdateTime: "2019-12-20T04:37:02Z"
    message: ReplicaSet "taurus-stats-ms-75ddcf9944" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-12-20T04:37:08Z"
    lastUpdateTime: "2019-12-20T04:37:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 39
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
