apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "20"
    field.cattle.io/creatorId: user-fvqkl
    field.cattle.io/publicEndpoints: '[{"addresses":["18.206.81.12"],"port":443,"protocol":"HTTPS","serviceName":"default:taurus-gateway","ingressName":"default:taurusmaze.co","hostname":"taurusmaze.co","path":"/graphql","allNodes":true},{"addresses":["18.206.81.12"],"port":31517,"protocol":"TCP","serviceName":"default:taurus-gateway-nodeport","allNodes":true}]'
  creationTimestamp: "2019-12-17T02:35:54Z"
  generation: 22
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-taurus-gateway
  name: taurus-gateway
  namespace: default
  resourceVersion: "761375"
  selfLink: /apis/apps/v1/namespaces/default/deployments/taurus-gateway
  uid: 9d5768a9-c93a-4a85-908f-4e0aedb480dd
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-taurus-gateway
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-12-20T08:15:16Z"
        field.cattle.io/ports: '[[{"containerPort":4000,"dnsName":"taurus-gateway-nodeport","kind":"NodePort","name":"graphql","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-taurus-gateway
    spec:
      containers:
      - env:
        - name: DATA_STORE_URL
          value: http://taurus-data-store-ms:4000/graphql
        - name: REST_GATEWAY_URL
          value: http://taurus-rest-resolver:4000/graphql
        - name: STATS_URL
          value: http://18.206.81.12:30954/
        image: taurusgame/gateway
        imagePullPolicy: Always
        name: taurus-gateway
        ports:
        - containerPort: 4000
          name: graphql
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2019-12-19T21:19:08Z"
    lastUpdateTime: "2019-12-19T21:19:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-17T02:35:54Z"
    lastUpdateTime: "2019-12-20T08:15:25Z"
    message: ReplicaSet "taurus-gateway-59cd758b84" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 22
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
