apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "19"
    field.cattle.io/creatorId: user-fvqkl
    field.cattle.io/publicEndpoints: '[{"addresses":["18.206.81.12"],"port":30056,"protocol":"TCP","serviceName":"default:taurus-rest-resolver-nodeport","allNodes":true}]'
  creationTimestamp: "2019-12-17T02:28:55Z"
  generation: 20
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-taurus-rest-resolver
  name: taurus-rest-resolver
  namespace: default
  resourceVersion: "646760"
  selfLink: /apis/apps/v1/namespaces/default/deployments/taurus-rest-resolver
  uid: 9b833046-db0c-47a6-8140-dba79efd7941
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-taurus-rest-resolver
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-12-19T21:19:31Z"
        field.cattle.io/ports: '[[{"containerPort":4000,"dnsName":"taurus-rest-resolver-nodeport","kind":"NodePort","name":"graphql","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-taurus-rest-resolver
    spec:
      containers:
      - env:
        - name: AUTH_URL
          value: http://taurus-auth-ms:3000/
        - name: GAME_URL
          value: http://taurus-game-server-lb:3030/gs
        - name: GRID_URL
          value: http://taurus-grid-gen-ms:8080/
        image: taurusgame/rest-gateway
        imagePullPolicy: Always
        name: taurus-rest-resolver
        ports:
        - containerPort: 4000
          name: graphql
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2019-12-19T21:19:34Z"
    lastUpdateTime: "2019-12-19T21:19:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-17T02:28:55Z"
    lastUpdateTime: "2019-12-19T21:19:40Z"
    message: ReplicaSet "taurus-rest-resolver-ff58f8cdd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 20
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
