apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    field.cattle.io/creatorId: user-fvqkl
    field.cattle.io/publicEndpoints: "null"
  creationTimestamp: "2019-12-17T01:54:32Z"
  generation: 9
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-taurus-stats-db
  name: taurus-stats-db
  namespace: default
  resourceVersion: "494139"
  selfLink: /apis/apps/v1/namespaces/default/deployments/taurus-stats-db
  uid: 1f035d71-f884-4722-a6f5-6dc851ac065d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-taurus-stats-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-12-19T05:23:08Z"
        field.cattle.io/ports: '[[{"containerPort":3306,"dnsName":"taurus-stats-db","kind":"ClusterIP","name":"mysql","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-taurus-stats-db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: taurus-stats
        - name: MYSQL_PASSWORD
          value: t4urus
        - name: MYSQL_ROOT_PASSWORD
          value: cX8Lpfft
        - name: MYSQL_USER
          value: taurus
        image: mysql:5.7
        imagePullPolicy: Always
        name: taurus-stats-db
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-17T01:54:42Z"
    lastUpdateTime: "2019-12-17T01:54:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-17T01:54:32Z"
    lastUpdateTime: "2019-12-19T05:23:10Z"
    message: ReplicaSet "taurus-stats-db-5bddd7c69b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
