apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "17"
    field.cattle.io/creatorId: user-fvqkl
    field.cattle.io/publicEndpoints: '[{"addresses":["18.206.81.12"],"port":31130,"protocol":"TCP","serviceName":"default:taurus-game-server-lb-nodeport","allNodes":true},{"addresses":["18.206.81.12"],"port":443,"protocol":"HTTPS","serviceName":"default:taurus-game-server-lb","ingressName":"default:taurusmaze.co","hostname":"taurusmaze.co","path":"/gs","allNodes":true}]'
  creationTimestamp: "2019-12-17T19:25:10Z"
  generation: 19
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-taurus-game-server-lb
  name: taurus-game-server-lb
  namespace: default
  resourceVersion: "695018"
  selfLink: /apis/apps/v1/namespaces/default/deployments/taurus-game-server-lb
  uid: 539906fd-cc14-4236-83ff-e0e83c427ef6
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-taurus-game-server-lb
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-12-20T01:40:31Z"
        field.cattle.io/ports: '[[{"containerPort":3030,"dnsName":"taurus-game-server-lb-nodeport","kind":"NodePort","name":"go","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-taurus-game-server-lb
    spec:
      containers:
      - env:
        - name: API_PREFIX
          value: /gs
        - name: SERVER_LIST
          value: taurus-game-server-ms-0:8080,taurus-game-server-ms-1:8080,taurus-game-server-ms-2:8080,taurus-game-server-ms-3:8080
        image: taurusgame/game-server-lb
        imagePullPolicy: Always
        name: taurus-game-server-lb
        ports:
        - containerPort: 3030
          name: go
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2019-12-19T21:18:34Z"
    lastUpdateTime: "2019-12-19T21:18:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-17T19:25:10Z"
    lastUpdateTime: "2019-12-20T01:40:41Z"
    message: ReplicaSet "taurus-game-server-lb-69bc6f76c9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 19
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
