apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "41"
    field.cattle.io/creatorId: user-fvqkl
    field.cattle.io/publicEndpoints: '[{"addresses":["18.206.81.12"],"port":32375,"protocol":"TCP","serviceName":"default:taurus-auth-ms-nodeport","allNodes":true}]'
  creationTimestamp: "2019-12-17T02:05:43Z"
  generation: 42
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-taurus-auth-ms
  name: taurus-auth-ms
  namespace: default
  resourceVersion: "712113"
  selfLink: /apis/apps/v1/namespaces/default/deployments/taurus-auth-ms
  uid: 866da02d-f1b7-4b5c-8658-4e6460827406
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-taurus-auth-ms
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-12-20T03:12:46Z"
        field.cattle.io/ports: '[[{"containerPort":3000,"dnsName":"taurus-auth-ms-nodeport","kind":"NodePort","name":"3000tcp01","protocol":"TCP"},{"containerPort":3000,"dnsName":"taurus-auth-ms","kind":"ClusterIP","name":"3000tcp02","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-taurus-auth-ms
    spec:
      containers:
      - env:
        - name: DEVISE_JWT_SECRET_KEY
          value: df20b9f114c31d3cff8dc50ddd633590a1ca63d15d8a9d1937a8265f889841d4919757e9bf7d38e22bed4dc15469b49e3016940a9a3bbc98a135e21d65e5f72a
        - name: LDAP_ADMIN
          value: admin
        - name: LDAP_ADMIN_PASSWORD
          value: admin
        - name: LDAP_HOST
          value: taurus-ldap
        - name: LDAP_PORT
          value: "389"
        - name: PASSWORD_DB
          value: postgres
        - name: RAILS_MAX_THREADS
          value: "100"
        - name: SECRET_KEY_BASE
          value: asdfsadfsaf
        - name: SES_PASSWORD
          value: BJ5OB5jPcwtTo1QW42PuOtv9x2lzrZ5S1rJJqrXfeVGG
        - name: SES_SERVER
          value: email-smtp.us-east-1.amazonaws.com
        - name: SES_USERNAME
          value: AKIAVATJKTMLWACJQM7M
        - name: URL_DB
          value: taurus-auth-db
        - name: URL_WEB
          value: https://taurusmaze.co
        - name: USER_DB
          value: postgres
        image: taurusgame/auth-ms:v2
        imagePullPolicy: Always
        name: taurus-auth-ms
        ports:
        - containerPort: 3000
          name: 3000tcp01
          protocol: TCP
        - containerPort: 3000
          name: 3000tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2019-12-19T21:18:25Z"
    lastUpdateTime: "2019-12-19T21:18:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-17T02:05:43Z"
    lastUpdateTime: "2019-12-20T03:12:57Z"
    message: ReplicaSet "taurus-auth-ms-865cd87d9f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 42
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
