apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "25"
    field.cattle.io/creatorId: user-fvqkl
    field.cattle.io/publicEndpoints: '[{"addresses":["18.206.81.12"],"port":31723,"protocol":"TCP","serviceName":"default:taurus-data-store-ms-nodeport","allNodes":true}]'
  creationTimestamp: "2019-12-17T00:48:32Z"
  generation: 28
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-taurus-data-store-ms
  name: taurus-data-store-ms
  namespace: default
  resourceVersion: "735016"
  selfLink: /apis/apps/v1/namespaces/default/deployments/taurus-data-store-ms
  uid: fb671bc4-f12f-473a-a54e-6fe272dc2eb0
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-taurus-data-store-ms
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-12-20T05:26:30Z"
        field.cattle.io/ports: '[[{"containerPort":4000,"dnsName":"taurus-data-store-ms-nodeport","kind":"NodePort","name":"4000tcp01","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-taurus-data-store-ms
    spec:
      containers:
      - env:
        - name: MONGO_URL
          value: mongodb://taurus-data-store-db-0:27017
        - name: STATS_URL
          value: http://taurus-stats-ms:5001/match
        image: taurusgame/data-store-ms
        imagePullPolicy: Always
        name: taurus-data-store-ms
        ports:
        - containerPort: 4000
          name: 4000tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2019-12-20T05:26:32Z"
    lastUpdateTime: "2019-12-20T05:26:32Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-17T00:48:32Z"
    lastUpdateTime: "2019-12-20T05:26:33Z"
    message: ReplicaSet "taurus-data-store-ms-c877bc88c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 28
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
